/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	time "time"

	trainink8sv1alpha1 "github.com/ChinmayaSharma-hue/TrainInKubes/pkg/apis/trainink8s/v1alpha1"
	versioned "github.com/ChinmayaSharma-hue/TrainInKubes/pkg/client/clientset/versioned"
	internalinterfaces "github.com/ChinmayaSharma-hue/TrainInKubes/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/ChinmayaSharma-hue/TrainInKubes/pkg/client/listers/trainink8s/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// TrainInKubeInformer provides access to a shared informer and lister for
// TrainInKubes.
type TrainInKubeInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.TrainInKubeLister
}

type trainInKubeInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewTrainInKubeInformer constructs a new informer for TrainInKube type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewTrainInKubeInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredTrainInKubeInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredTrainInKubeInformer constructs a new informer for TrainInKube type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredTrainInKubeInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.FooV1alpha1().TrainInKubes(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.FooV1alpha1().TrainInKubes(namespace).Watch(context.TODO(), options)
			},
		},
		&trainink8sv1alpha1.TrainInKube{},
		resyncPeriod,
		indexers,
	)
}

func (f *trainInKubeInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredTrainInKubeInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *trainInKubeInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&trainink8sv1alpha1.TrainInKube{}, f.defaultInformer)
}

func (f *trainInKubeInformer) Lister() v1alpha1.TrainInKubeLister {
	return v1alpha1.NewTrainInKubeLister(f.Informer().GetIndexer())
}
