apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: traininkubes.trainink8s.com
spec:
  group: trainink8s.com
  versions:
    - name: v1alpha1
      served: true 
      storage: true 
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                modelImage:
                  type: string
                modelImagePullPolicy:
                  type: string
                trainingImage:
                  type: string
                trainingImagePullPolicy:
                  type: string
                epochs:
                  type: integer
                preprocessedDatasetLocation:
                  type: string
                splitDatasetLocation:
                  type: string
                modelsLocation:
                  type: string
              allOf:
                - required:
                  - modelImage
                  - modelImagePullPolicy
                  - trainingImage
                  - trainingImagePullPolicy
                  - epochs
                  - preprocessedDatasetLocation
                  - splitDatasetLocation
                  - modelsLocation
  scope: Namespaced
  names:
    plural: traininkubes
    singular: traininkube
    kind: TrainInKube
    shortNames:
    - tik
